default_agent: quaki
agents:
  agentcore_lang_runtime:
    name: agentcore_lang_runtime
    entrypoint: C:/Users/ajayr/Desktop/quaki-customer-agent/01_agentcore_runtime.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\ajayr\Desktop\quaki-customer-agent
    aws:
      execution_role: arn:aws:iam::125975759762:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-c980c3716d
      execution_role_auto_create: false
      account: '125975759762'
      region: us-east-2
      ecr_repository: 125975759762.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-agentcore_lang_runtime
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: agentcore_lang_runtime-1C0mWi4Ajd
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:125975759762:runtime/agentcore_lang_runtime-1C0mWi4Ajd
      agent_session_id: 1a6bcbdd-2a30-46b8-81df-01e1e3ba02c7
    codebuild:
      project_name: bedrock-agentcore-agentcore_lang_runtime-builder
      execution_role: arn:aws:iam::125975759762:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-c980c3716d
      source_bucket: bedrock-agentcore-codebuild-sources-125975759762-us-east-2
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
  quaki:
    name: quaki
    entrypoint: C:/Users/ajayr/Desktop/quaki-customer-agent/02_agentcore_memory.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\ajayr\Desktop\quaki-customer-agent
    aws:
      execution_role: arn:aws:iam::125975759762:role/AmazonBedrockAgentCoreSDKRuntime-us-east-2-15f0cbd273
      execution_role_auto_create: false
      account: '125975759762'
      region: us-east-2
      ecr_repository: 125975759762.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-quaki
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: quaki-jLdRKv6u8W
      agent_arn: arn:aws:bedrock-agentcore:us-east-2:125975759762:runtime/quaki-jLdRKv6u8W
      agent_session_id: concise-test-20260206-225800abcdef
    codebuild:
      project_name: bedrock-agentcore-quaki-builder
      execution_role: arn:aws:iam::125975759762:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-2-15f0cbd273
      source_bucket: bedrock-agentcore-codebuild-sources-125975759762-us-east-2
    memory:
      mode: STM_AND_LTM
      memory_id: quaki_customer_care_agent_memory-nzvliw7L6V
      memory_arn: null
      memory_name: quaki_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
