version: 0.2
phases:
  build:
    commands:
      - echo "Building Docker image with no cache..."
      - docker build --no-cache -t bedrock-agentcore-arm64 .
      - echo "Logging into ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 125975759762.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-quaki
      - echo "Tagging image with $IMAGE_TAG..."
      - docker tag bedrock-agentcore-arm64:latest 125975759762.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-quaki:$IMAGE_TAG
  post_build:
    commands:
      - echo "Pushing image to ECR..."
      - docker push 125975759762.dkr.ecr.us-east-2.amazonaws.com/bedrock-agentcore-quaki:$IMAGE_TAG
      - echo "Build completed"
